services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  db:
    image: postgres:15.0-alpine
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
