services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test-db:
    image: postgres:15.0-alpine
    env_file:
      - db.env
    environment:
      POSTGRES_USER: "testUser"
      POSTGRES_PASSWORD: "testUser"
      POSTGRES_DB: "testUser"
    ports:
      - '5433:5432'
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  test-db-data:
